#!/usr/bin/env python3
"""
Claude-powered code review for GitHub Actions CI.

Reads environment:
    ANTHROPIC_API_KEY   — required; skips review if absent
    BASE_REF            — base branch name (default: main)
    GITHUB_SERVER_URL   — used to build a CI run link in the comment
    GITHUB_REPOSITORY   — owner/repo
    GITHUB_RUN_ID       — numeric run ID

Writes review markdown to claude_review.md (picked up by actions/github-script
to post as a PR comment).
"""

import os
import subprocess
import sys

# anthropic is installed in the review job step before this script runs
try:
    import anthropic
except ImportError:
    print("anthropic package not installed")
    sys.exit(1)

OUTPUT_FILE    = "claude_review.md"
MAX_DIFF_CHARS = 8_000   # ~2 k tokens; leaves headroom for the response
MAX_FILE_CHARS = 2_500   # per changed file

REVIEW_SYSTEM = """You are a senior Python engineer reviewing a pull request for a voice \
shopping bot backend.
Stack: FastAPI · LangGraph · Anthropic Claude API · Langfuse (observability)

Review the diff for:
1. **Correctness** — logic bugs, unhandled edge cases, wrong assumptions
2. **Security** — API key exposure, injection risks, missing input validation
3. **Performance** — sync-blocking calls in async context, missing timeouts, \
redundant Claude API calls
4. **Patterns** — FastAPI / LangGraph best practices, Langfuse tracing coverage, \
circular-import hygiene

Format your response as GitHub-flavored Markdown with exactly these sections:

## Summary
One or two sentences on what changed and the overall impression.

## Issues
- List only real problems. Omit this section entirely if there are none.

## Suggestions
- Non-blocking improvements. Omit this section entirely if there are none.

## Verdict
One of: ✅ LGTM | ⚠️ LGTM with suggestions | 🔴 Changes requested

Keep it under 500 words. Skip praise for standard boilerplate."""


def _run(cmd: list[str]) -> str:
    return subprocess.run(cmd, capture_output=True, text=True).stdout


def changed_python_files(base_ref: str) -> list[str]:
    """Return .py files changed vs the base branch that still exist on disk."""
    raw = _run(["git", "diff", "--name-only", f"origin/{base_ref}...HEAD"])
    return [
        f for f in raw.strip().splitlines()
        if f.endswith(".py") and os.path.exists(f)
    ]


def build_context(files: list[str], base_ref: str) -> str:
    """Assemble the diff + file contents into a single review prompt."""
    diff = _run(["git", "diff", f"origin/{base_ref}...HEAD", "--"] + files)

    ctx  = f"**Changed files:** `{'`, `'.join(files)}`\n\n"
    ctx += "### Diff\n```diff\n"
    ctx += diff[:MAX_DIFF_CHARS]
    if len(diff) > MAX_DIFF_CHARS:
        ctx += f"\n... (diff truncated after {MAX_DIFF_CHARS} characters)\n"
    ctx += "```\n"

    for path in files:
        try:
            content = open(path).read()
        except OSError:
            continue
        ctx += f"\n### Current `{path}`\n```python\n"
        ctx += content[:MAX_FILE_CHARS]
        if len(content) > MAX_FILE_CHARS:
            ctx += f"\n... (file truncated after {MAX_FILE_CHARS} characters)\n"
        ctx += "```\n"

    return ctx


def write_output(body: str) -> None:
    """Write the review (or a skip notice) to OUTPUT_FILE."""
    srv  = os.environ.get("GITHUB_SERVER_URL", "https://github.com")
    repo = os.environ.get("GITHUB_REPOSITORY", "")
    run  = os.environ.get("GITHUB_RUN_ID", "")

    footer = "\n\n---\n*🤖 Generated by [Claude](https://claude.ai) · claude-sonnet-4-5*"
    if run and repo:
        footer += f" · [CI run #{run}]({srv}/{repo}/actions/runs/{run})"

    with open(OUTPUT_FILE, "w") as fh:
        fh.write(f"## 🤖 Claude Code Review\n\n{body}{footer}\n")

    print(f"Review written to {OUTPUT_FILE}")


def main() -> None:
    api_key  = os.environ.get("ANTHROPIC_API_KEY", "")
    base_ref = os.environ.get("BASE_REF", "main")

    if not api_key:
        write_output("_Review skipped — `ANTHROPIC_API_KEY` is not configured for this workflow._")
        return

    files = changed_python_files(base_ref)
    if not files:
        write_output("_No Python files changed in this PR — nothing to review._")
        return

    print(f"Reviewing {len(files)} file(s): {', '.join(files)}")
    context = build_context(files, base_ref)

    client = anthropic.Anthropic(api_key=api_key)
    try:
        resp   = client.messages.create(
            model="claude-sonnet-4-5",
            max_tokens=1024,
            system=REVIEW_SYSTEM,
            messages=[{"role": "user", "content": context}],
        )
        review = resp.content[0].text
    except Exception as exc:
        review = f"_Review failed with an API error: `{exc}`_"

    write_output(review)


if __name__ == "__main__":
    main()
